### ISSUE TITLE
Publish the solution to GitHub Pages

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bpmn-visualization-tutorial-getting-started#4]
This will let users see what they are going to develop.
**Use github actions** to publish to github pages https://github.blog/2022-08-10-github-pages-now-uses-actions-by-default/ and **not a branch**. We don't need to keep history of the application and the GH actions are much more flexible than publishing using branches (in particular, Jekkyl is not involved).

Tasks
- [x] Setup automation: publish when the code changes in the `solution` branch
- [x] Add link to the github pages environment in the repo description
- [x] Add link in the README of the `develop` branch
- [x] Add link in the README of the `solution` branch

**Comment by tbouffard** [comment]
@csouchet the current configuration is wrong as it relies on branches and try to deploy the solution branch
So there are errors when accessing to the page. I see a blank page and I got this error in the console
```
Uncaught TypeError: Error while resolving the module specifier "bpmn-visualization".
Relative module specifiers must start with "./", "../" or " /".
```

**Pages settings**

![image](https://user-images.githubusercontent.com/27200110/195424608-b7f5a177-c48c-4f28-9aae-38a24410c024.png)


**gh-pages environment settings**

![image](https://user-images.githubusercontent.com/27200110/195425266-cc81e753-9e20-47cd-95cf-80be4afdc4a6.png)

**Comment by csouchet** [comment]
@tbouffard It's not finished. I just start at the end of the day yesterday.
I tried to copy the configuration of https://github.com/process-analytics/bpmn-visualization-js and copy the workflow to generate the documentation.

**Comment by tbouffard** [comment]
> @tbouffard It's not finished. I just start at the end of the day yesterday. I tried to copy the configuration of https://github.com/process-analytics/bpmn-visualization-js and copy the workflow to generate the documentation.

this won't work to use the "github actions" mode as bpmn-visualization is using the "branch" mode

**Comment by csouchet** [comment]
> > @tbouffard It's not finished. I just start at the end of the day yesterday. I tried to copy the configuration of https://github.com/process-analytics/bpmn-visualization-js and copy the workflow to generate the documentation.
> 
> this won't work to use the "github actions" mode as bpmn-visualization is using the "branch" mode

This is what I try to do 😆

**Comment by csouchet** [comment]
@tbouffard I changed the source. 
![image](https://user-images.githubusercontent.com/4921914/195636956-99ff8ab1-3cf1-46a2-989e-e15b6859c984.png)

But we need to have a workflow, and I don't understand what we have to do.
So, if you want to continue with @assynour, I let you this issue with pleasure 🙂
